### ISSUE TITLE
License

### ISSUE THREAD

**Issue by leberechtreinhold** [zHaytam/EasyLocalization#1]
This project looks great, it's small but powerful. However right now it doesn't have a license, which means it's under exclusive copyright, making it very hard to use on most projects.

Of course if that's your intention to retain exclusive copyright it's ok, but if it's not, could you please put a license file with MIT or whatever you like? For example https://choosealicense.com/licenses/mit

**Comment by zHaytam** [comment]
Hello, it's done! This project was just me trying things out, totally forgot about a license.
Thanks!
